Update README.md
Hi, i am Simon, i am new to github, just wanted to ask if the mentioned python3-pybluez at the setup-section (readme) meant to be python3-bluez (couldnt find the mentioned package at kubuntu-linux-stable atm).

and also I cloned the git-repository, tried to execute, got an error stating that some setuptools are missing.

`Traceback (most recent call last):
  File "/home/simon/files/Programme-why-ever/USB-multimeter_ruideng-bluetooth/rdumtool/./setup.py", line 5, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
`

so I installed:

`aptitude install python3-setuptools`

I Hope this contact isnt received-unpolitely, didnt know how else to ask this question, thankyou for coding this software! I am really curious to use it (and I cannot code myself like this).

sincerely yours simon
(is this pull request publicially visible? dude.. i am such a noob :-D)